name: DevOps Session

on: 
  push:
  #pull_request:
    branches: ["test"]

jobs:
  Build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: package docker image
      run: |
        #sudo apt update
        echo "DevOps first CI/CD with github actions"
        docker build . --file Dockerfile -t Bank-App:$(date)
